const brandColors = {
  light: {
    highlight: '#bf4e30',
    primary: '#397367',
    secondary: '#f5f5f5',
    tertiary: 'rgb(194, 194, 194)',
    dark: '#1A1A1A',
    light: '#ffffff',
  },
  dark: {
    highlight: '#bf4e30',
    primary: '#397367',
    secondary: '#42858C',
    dark: '#1A1A1A',
    light: '#D7D9DA',
  },
};

export const Colors = {
  light: {
    text: '#11181C',
    textMuted: '#687076',
    background: brandColors.light.secondary,
    surface: brandColors.light.tertiary,
    primary: brandColors.light.highlight,
    border: '#4e4e4e',
    icon: '#687076',
    whiteKey: '#FFFFFF',
    blackKey: '#1A1A1A',
    correctFeedback: brandColors.light.primary,
    incorrectFeedback: brandColors.light.highlight,
    noteDisplay: brandColors.light.highlight,
    noteDisplayText: brandColors.light.light,
    blackKeyBorder: '#444444',
    whiteKeyBorder: '#292929',
    staffBackground: '#FFFFFF',
    staffLine: '#11181C',
    staffNote: brandColors.light.highlight,
    staffAccidental: brandColors.light.highlight,
  },
  dark: {
    text: '#d7d9da',
    textMuted: '#9BA1A6',
    background: brandColors.dark.dark,
    surface: '#1f2123',
    primary: brandColors.dark.highlight,
    border: '#3a3a3a',
    icon: '#9BA1A6',
    whiteKey: '#999999',
    blackKey: '#1A1A1A',
    correctFeedback: brandColors.dark.primary,
    incorrectFeedback: brandColors.dark.highlight,
    noteDisplay: brandColors.dark.highlight,
    noteDisplayText: brandColors.dark.light,
    blackKeyBorder: '#444444',
    whiteKeyBorder: '#CCCCCC',
    staffBackground: '#1A1A1A',
    staffLine: '#d7d9da',
    staffNote: brandColors.dark.highlight,
    staffAccidental: brandColors.dark.highlight,
  },
} as const;

export type ColorName = keyof (typeof Colors)['light'];
export type Theme = keyof typeof Colors;
